version: '2'
services:
    printarchiver-app:
        image: printarchiver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://printarchiver-mysql:3306/printarchiver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    printarchiver-mysql:
        extends:
            file: mysql.yml
            service: printarchiver-mysql
